kind: pipeline
name: default

steps:
- name: test
  image: brazildatacube/r-webservices:1.0.0
  commands:
  - apt-get update & apt-get install pandoc-citeproc -y
  - R CMD build .
  - R CMD check *.tar.gz >&1 | tee stdfile && cat stdfile | grep -E "(WARNING|ERROR)" > /dev/null | test $? -eq 1

- name: coverage
  image: brazildatacube/r-webservices:1.0.0
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
  commands:
  - R -e 'library(covr); codecov(quiet = FALSE)'
  when:
    event:
    - push

- name: discord-notify
  image: brazildatacube/bdc-drone-discord
  settings:
    webhook:
      from_secret: discord_webhook
  when:
    status:
      - failure
      - success
