default:


    # Names of the providers of services
    WTSS_providers          : ["WTSS-INPE"]

    # URL to access each WTSS service
    WTSS-INPE_server        : "http://www.esensing.dpi.inpe.br/wtss/"


    supported_satellites    : ["TERRA", "AQUA", "MODIS", "LANDSAT8", "LANDSAT"]
    supported_sensors       : ["MODIS", "OLI"]

    MODIS_sensors           : ["MODIS"]
    TERRA_sensors           : ["MODIS"]
    LANDSAT8_sensors        : ["OLI"]
    LANDSAT_sensors         : ["OLI"]

    MODIS_products          : ["MOD13Q1"]
    MOD13Q1_satellite       : ["TERRA"]
    MOD13Q1_sensor          : ["MODIS"]

    MODIS                   :
        missing_value       :
            ndvi            : -3000
            evi             : -3000
            red             : -1000
            nir             : -1000
            blue            : -1000
            mir             : -1000

        minimum_value       :
            ndvi            : -3000
            evi             : -3000
            red             : 0
            blue            : 0
            nir             : 0
            mir             : 0

        maximum_value       :
            ndvi            : 10000
            evi             : 10000
            red             : 10000
            blue            : 10000
            nir             : 10000
            mir             : 10000

        scale_factor        :
            ndvi            : 0.0001
            evi             : 0.0001
            red             : 0.0001
            nir             : 0.0001
            blue            : 0.0001
            mir             : 0.0001

        resolution          :
            xres            : 0.00208334
            yres            : 0.00208334

    OLI                     :
        missing_value       :
            ndvi            : -9999
            evi             : -9999
            blue            : -9999
            red             : -9999
            nir             : -9999
            swir1           : -9999
            swir2           : -9999

        minimum_value       :
            ndvi            : -3000
            evi             : -3000
            red             : 0
            blue            : 0
            nir             : 0
            swir1           : 0
            swir2           : 0

        maximum_value       :
            ndvi            : 10000
            evi             : 10000
            red             : 10000
            blue            : 10000
            nir             : 10000
            swir1           : 10000
            swir2           : 10000

        scale_factor:
            ndvi            : 0.0001
            evi             : 0.0001
            red             : 0.0001
            nir             : 0.0001
            swir1           : 0.0001
            swir2           : 0.0001

        resolution          :
            xres            : 30
            yres            : 30






